/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MasterResume } from '../src/types';

export const VERIFIED_MASTER_RESUME: MasterResume = {
  id: 'resume-master-001',
  user_id: 'user-bhargav-001',
  version: 1,
  is_active: true,
  is_seed_data: true,
  source_of_truth: {
    is_verified: true,
    source: 'seed_specification',
    last_verified_at: '2026-09-11',
    verified_by: 'Master Specification Audit',
  },
  personal_information: {
    full_name: 'Bhargav Aravind Sai Ram Choppa',
    email: 'bhargavchoppa23@gmail.com',
    phone: '+1 (860) 555-0192',
    location: 'Hartford, CT / Boston, MA (Open to USA & India)',
    linkedin_url: 'https://linkedin.com/in/bhargav-choppa',
    header_positioning:
      'Business Analyst | Product Owner | CSM | CSPO | PMP | AWS & Azure Certified',
  },
  professional_summary:
    'Accomplished Business Analyst and Product Owner with ~9 years of verified cross-functional experience across Semiconductor Manufacturing, Public Sector Health Eligibility Systems, FinTech Bridge Architectures, Financial Market Data Platforms, and E-Commerce Digital Payments. Proven track record in steering product roadmaps from ideation to delivery, leading Agile ceremonies, conducting market research, formulating pricing strategies, and authoring rigorous BRDs, User Stories, and Traceability Matrices.',
  total_experience_years: 9,
  is_immutable: true,
  last_updated: '2026-09-11',
  inconsistency_flags: [
    {
      id: 'FLAG-PMP-001',
      code: 'HEADER_CERTIFICATION_MISMATCH',
      severity: 'high',
      title: 'Potential resume inconsistency — verify PMP certification.',
      description:
        'Header: PMP. Certification section: PMP not listed. Display: Potential resume inconsistency — verify PMP certification. Do NOT automatically add PMP.',
      location_a: 'personal_information.header_positioning',
      location_b: 'certifications',
      resolution_rule:
        'STRICT AUDIT RULE: Never invent, fabricate, or silently add PMP into certifications. Flag clearly in ATS audit reports and warn user before generating executive summaries.',
    },
  ],
  skills: [
    'Business Analysis',
    'Product Roadmapping',
    'Feature Prioritization',
    'Agile / Scrum',
    'Sprint Planning',
    'User Stories & Acceptance Criteria',
    'BRD (Business Requirements Document)',
    'Process & Workflow Modeling',
    'System Analysis',
    'Impact Assessments',
    'Feasibility Studies',
    'Requirements Traceability Matrix (RTM)',
    'A/B Testing',
    'Customer Insights & Advocacy',
    'Stakeholder Management & Collaboration',
    'Market Research & Competitor Analysis',
    'Pricing Strategy & Financial Forecasting',
    'Go-to-Market (GTM) Strategy',
    'User Acceptance Testing (UAT)',
    'Process Automation',
    'Cross-Functional Leadership',
  ],
  technologies: [
    'Tableau',
    'Power BI',
    'AWS QuickSight',
    'Google Analytics',
    'SQL',
    'Statistical Analysis',
    'BI & Data Visualization',
    'Jira',
    'Confluence',
    'Azure DevOps',
    'Rally',
    'AWS (Amazon Web Services)',
    'Microsoft Azure',
    'REST API',
    'JSON',
    'XML',
    'GitHub',
    'GitLab',
    'Postman',
    'Cloud Solutions Architecture',
  ],
  experience: [
    {
      id: 'exp-001',
      company: 'MIT Resources',
      title: 'Business Analyst',
      location: 'Hartford, Connecticut',
      start_date: 'Aug 2023',
      end_date: 'Present',
      is_current: true,
      responsibilities: [
        'Steer the product roadmap for advanced semiconductor wafer fabrication technologies, translating complex engineering parameters into high-impact customer-facing features.',
        'Synthesize market research and quantitative customer insights to align engineering, manufacturing, and global sales departments on key product deliverables.',
        'Provide dedicated global customer technical product and application support for advanced wafer manufacturing lines.',
        'Formulate data-driven pricing models and financial forecasting leveraging Tableau and Power BI analytical dashboards.',
        'Lead executive prioritization sessions and customer advocacy forums to resolve technical tradeoffs and accelerate contract discussions.',
      ],
      achievements: [
        'Engineered predictive financial forecasting models in Tableau/Power BI that informed executive contract negotiations.',
        'Bridged global customer technical escalations directly into manufacturing release sprints, drastically reducing feedback turnaround.',
      ],
      technologies: ['Tableau', 'Power BI', 'SQL', 'Jira', 'Confluence', 'Cloud Solutions Architecture'],
      industry: 'Semiconductor Manufacturing & Hardware Engineering',
      domain: 'Wafer Fabrication, Industrial Analytics & Supply Chain',
    },
    {
      id: 'exp-002',
      company: 'Kyyba',
      title: 'Senior Business Analyst',
      location: 'Boston, Massachusetts',
      start_date: 'Nov 2022',
      end_date: 'Aug 2023',
      is_current: false,
      responsibilities: [
        'Directed the end-to-end product roadmap for a large-scale enterprise Integrated Eligibility and Enrollment System.',
        'Governed feature delivery, technical tradeoffs, and sprint milestones across engineering, platform architecture, and system integration teams.',
        'Extracted and operationalized customer insights to automate manual state-level eligibility workflows.',
        'Instituted operational KPI dashboards and business intelligence reporting inside Jira and Agile frameworks.',
      ],
      achievements: [
        'Spearheaded process automation and eligibility workflow streamlining that achieved a 30% operational effectiveness improvement.',
        'Delivered complex regulatory integration sprints ahead of multi-agency compliance deadlines.',
      ],
      technologies: ['Jira', 'Confluence', 'Agile/Scrum', 'BI Dashboards', 'Process Automation', 'REST API'],
      industry: 'Public Sector & Health and Human Services (HHS)',
      domain: 'Enterprise Eligibility, Enrollment Platforms & State Digital Services',
    },
    {
      id: 'exp-003',
      company: 'Client Server Technology Solutions',
      title: 'Business Analyst',
      location: 'New Jersey',
      start_date: 'Jun 2022',
      end_date: 'Nov 2022',
      is_current: false,
      responsibilities: [
        'Defined and delivered the product roadmap for enterprise bridge software orchestrating data exchange between disparate financial data platforms.',
        'Evaluated cloud architecture and informed core technology decisions alongside principal software engineers and operational leads.',
        'Analyzed technical architecture versus pricing tradeoffs to establish go-to-market (GTM) pricing tiers.',
        'Chaired user acceptance testing (UAT), regression cycles, and user advocacy councils across customer testing groups.',
      ],
      achievements: [
        'Engineered bridge software specifications enabling seamless bidirectional data synchronization across legacy and modern cloud finance systems.',
        'Standardized UAT acceptance criteria that cut post-deployment defects by over 25%.',
      ],
      technologies: ['Cloud Architecture', 'AWS', 'Azure', 'REST API', 'JSON', 'XML', 'Postman', 'UAT'],
      industry: 'Financial Technology (FinTech)',
      domain: 'Financial Data Integration, Cloud Middleware & API Interoperability',
    },
    {
      id: 'exp-004',
      company: 'FactSet',
      title: 'Associate Product Specialist',
      location: 'New York',
      start_date: 'May 2021',
      end_date: 'May 2022',
      is_current: false,
      responsibilities: [
        'Contributed to the financial services product roadmap, developing technical feature specifications for financial analysis suites.',
        'Conducted competitor market research and pricing strategy analysis to optimize product profitability and adoption.',
        'Collaborated with marketing to execute targeted digital campaigns and delivered technical sales support for institutional finance clients.',
        'Authored in-depth technical documentation, API specifications, and product release guides for investment professionals.',
      ],
      achievements: [
        'Synthesized market research that directly informed the rollout of a refreshed pricing tier for institutional market data feeds.',
        'Assisted technical sales teams on complex institutional client RFPs and bespoke workflow integrations.',
      ],
      technologies: ['Tableau', 'SQL', 'Postman', 'REST API', 'Market Research', 'Technical Documentation'],
      industry: 'Capital Markets & Financial Data',
      domain: 'Investment Analytics, Market Data Feeds & FinTech Workstations',
    },
    {
      id: 'exp-005',
      company: 'TCS',
      title: 'Business Analyst',
      location: 'Hyderabad, India',
      start_date: 'Sep 2019',
      end_date: 'Apr 2021',
      is_current: false,
      responsibilities: [
        'Functioned as primary product roadmap liaison bridging cross-border engineering teams with e-commerce and banking stakeholders.',
        'Conducted rigorous business problem decomposition, authored comprehensive BRDs, process flow diagrams, and workflow models.',
        'Drove digital payment integration initiatives, coordinating functional, non-functional, performance, reliability, and security testing.',
        'Coordinated technical integrations with third-party payment gateways and strategic banking partners.',
      ],
      achievements: [
        'Architected end-to-end payment workflow models ensuring ISO/PCI-DSS regulatory compliance across digital transaction corridors.',
        'Delivered 100% test scenario coverage across functional and security integration matrices.',
      ],
      technologies: ['BRD', 'User Stories', 'Workflow Modeling', 'Digital Payments', 'SQL', 'JSON', 'Jira', 'Rally'],
      industry: 'Banking, Financial Services & E-Commerce',
      domain: 'Core Banking, Digital Payments & Transaction Gateways',
    },
    {
      id: 'exp-006',
      company: 'SS Engineering Academy',
      title: 'Business Analyst Intern',
      location: 'Vijayawada, India',
      start_date: 'Jul 2016',
      end_date: 'May 2017',
      is_current: false,
      responsibilities: [
        'Supported roadmap implementation and executed change management initiatives across academic software systems.',
        'Conducted extensive competitor benchmarking across 5 industry-leading cloud education and learning management platforms.',
        'Evaluated emerging cloud education market trends to prioritize 3 high-impact product improvements.',
      ],
      achievements: [
        'Formulated competitive matrix evaluating 5 ed-tech platforms that prioritized 3 high-adoption student portal enhancements.',
      ],
      technologies: ['Competitor Analysis', 'Cloud Education Analysis', 'Process Modeling', 'Change Management'],
      industry: 'EdTech / Cloud Learning Systems',
      domain: 'Academic Portals, Student Information Systems & Cloud Learning',
    },
  ],
  education: [
    {
      id: 'edu-001',
      degree: 'Master of Technology (M.Tech)',
      field_of_study: 'Computer Science and Engineering',
      institution: 'Amity University',
      graduation_date: 'May 2019',
      location: 'India',
    },
    {
      id: 'edu-002',
      degree: 'Bachelor of Technology (B.Tech)',
      field_of_study: 'Computer Science and Engineering',
      institution: 'Vignan University',
      graduation_date: 'May 2016',
      location: 'India',
    },
  ],
  certifications: [
    {
      id: 'cert-001',
      name: 'CSPO (Certified Scrum Product Owner)',
      issuer: 'Scrum Alliance',
      verified: true,
      notes: 'Verified agile product leadership certification.',
    },
    {
      id: 'cert-002',
      name: 'CSM (Certified ScrumMaster)',
      issuer: 'Scrum Alliance',
      verified: true,
      notes: 'Verified agile facilitation and scrum mastery.',
    },
    {
      id: 'cert-003',
      name: 'AWS Certified Cloud Practitioner',
      issuer: 'Amazon Web Services',
      verified: true,
      notes: 'Verified foundational cloud architecture and billing concepts.',
    },
    {
      id: 'cert-004',
      name: 'AWS Cloud Financial Optimization Certified',
      issuer: 'Amazon Web Services',
      verified: true,
      notes: 'Verified cloud cost optimization and financial management.',
    },
    {
      id: 'cert-005',
      name: 'Microsoft Certified: Azure Fundamentals (AZ-900)',
      issuer: 'Microsoft',
      verified: true,
      notes: 'Verified Azure cloud services, security, and compliance.',
    },
    {
      id: 'cert-006',
      name: 'Product Launches Micro-Certification',
      issuer: 'ProductSchool',
      verified: true,
    },
    {
      id: 'cert-007',
      name: 'Product-Led Growth Micro-Certification',
      issuer: 'ProductSchool',
      verified: true,
    },
    {
      id: 'cert-008',
      name: 'Product Road Mapping Micro-Certification',
      issuer: 'ProductSchool',
      verified: true,
    },
    {
      id: 'cert-009',
      name: 'Product Strategy Micro-Certification',
      issuer: 'ProductSchool',
      verified: true,
    },
    {
      id: 'cert-010',
      name: 'Product Analytics Micro-Certification',
      issuer: 'ProductSchool',
      verified: true,
    },
  ],
  projects: [
    {
      id: 'proj-001',
      name: 'Semiconductor Wafer Yield & Pricing Intelligence Engine',
      description:
        'Engineered an analytical pricing and yield tracking pipeline combining Tableau dashboards with wafer telemetry data to assist executive negotiations with global fab customers.',
      technologies: ['Tableau', 'Power BI', 'SQL', 'Statistical Modeling'],
    },
    {
      id: 'proj-002',
      name: 'Public HHS Eligibility & Enrollment Modernization',
      description:
        'Architected operational workflows and automated eligibility rule evaluations, leading to a 30% operational effectiveness gain.',
      technologies: ['Jira', 'Process Modeling', 'Agile/Scrum', 'REST APIs'],
    },
    {
      id: 'proj-003',
      name: 'Cross-Platform Financial Middleware Bridge',
      description:
        'Designed bidirectional bridge specifications connecting institutional financial analysis endpoints with cloud storage architectures.',
      technologies: ['AWS', 'Azure', 'REST API', 'JSON', 'Postman'],
    },
  ],
  achievements: [
    'Spearheaded process automation in public eligibility platforms yielding a documented 30% operational effectiveness improvement.',
    'Formulated financial forecasting tools in Tableau/Power BI relied upon by executive leadership for multi-million dollar fab wafer agreements.',
    'Over 9 years of verified track record bridging deep technical engineering teams with high-stakes enterprise clients.',
  ],
};
